twig_component:
    anonymous_template_directory: 'components/'
    defaults:
        # Namespace & directory for components
        Shared\Twig\Components\: 'components/'
        Kantine\Twig\Components\: 'apps/kantine/templates/components/'
        Zeiterfassung\Twig\Components\: 'apps/zeiterfassung/templates/components/'

        