controllers:
    resource:
        path: ../src/Controller/
        namespace: Shared\Controller
    type: attribute

sonata_user_admin_security:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /zeiterfassung/admin

sonata_user_admin_resetting:
    resource: '@SonataUserBundle/Resources/config/routing/admin_resetting.xml'
    prefix: /zeiterfassung/admin

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /zeiterfassung/admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /zeiterfassung/admin